name = "tegaidogun-github-io"
compatibility_date = "2023-06-28"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm install && npx @cloudflare/next-on-pages"

[build.upload]
format = "service-worker"

[site]
bucket = ".next"

[env.production]
workers_dev = true 