name = "tegaidogun-github-io"
compatibility_date = "2023-06-28"
pages_build_output_dir = ".vercel/output/static"
compatibility_flags = ["nodejs_compat"]

[skip_files]
include = [
  ".next/cache/**",
  ".next/cache/webpack/**"
] 