name: Dependency Update Check

on:
  schedule:
    - cron: "0 0 */3 * *"
  workflow_dispatch:
  
permissions:
  contents: write
  pull-requests: write 


jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: npm install --global yarn

    - name: Install Dependencies
      run: yarn install

    - name: Update Dependencies
      run: yarn up "*"

    - name: Commit Changes
      run: |
        git config --global user.name "Eric Idogun"
        git config --global user.email "idogunoghenetega@gmail.com"
        git add .
        git commit -m "chore: update dependencies"

    - name: Push Changes and Create PR
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push origin HEAD:update-dependencies
        gh pr create --title "chore: update dependencies" --body "This PR updates outdated dependencies."
